#!/usr/bin/env sh
# Writes infra/.env for a self-hosted Webyz: the domain you pass, generated
# database passwords, and the optional settings left empty for you to fill.
#
#   ./setup.sh analytics.example.com
#
# Refuses to overwrite an existing .env. Set WEBYZ_ENV_FILE to write elsewhere.
set -eu

DOMAIN="${1:-}"
if [ -z "$DOMAIN" ]; then
  printf 'Domain for Webyz (e.g. analytics.example.com): '
  read -r DOMAIN
fi
DOMAIN="${DOMAIN#https://}"; DOMAIN="${DOMAIN#http://}"; DOMAIN="${DOMAIN%/}"
DOMAIN="$(printf '%s' "$DOMAIN" | tr '[:upper:]' '[:lower:]')"
case "$DOMAIN" in
  ""|*/*|*" "*) echo "A bare hostname is required, e.g. analytics.example.com" >&2; exit 1 ;;
esac

OUT="${WEBYZ_ENV_FILE:-$(dirname "$0")/.env}"
if [ -e "$OUT" ]; then
  echo "$OUT already exists; edit it or remove it first." >&2
  exit 1
fi

secret() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex 24
  else head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

cat > "$OUT" <<EOF
# Webyz configuration. Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%MZ).
# Every variable is documented in docs/configuration.md. Never commit this file.

# The one public hostname. The dashboard and the API share it; Caddy issues
# its certificate. BASE_URL must match DOMAIN with the scheme.
DOMAIN=$DOMAIN
BASE_URL=https://$DOMAIN

# Database passwords, used only inside the stack.
POSTGRES_PASSWORD=$(secret)
CLICKHOUSE_PASSWORD=$(secret)

# Encrypts stored Google credentials (Search Console). Keep it: changing it
# makes existing connections unreadable until they are reconnected.
ENCRYPTION_KEY=$(secret)$(secret)$(secret)$(secret | cut -c1-16)

# One reverse proxy (the bundled Caddy, or yours) in front of the API.
TRUST_PROXY=1

# Who can sign up. 'disabled' allows only the first account, which is yours;
# 'open' lets anyone register.
REGISTRATION=disabled

# Email confirmation for password signups: auto requires it only when
# RESEND_API_KEY is set (otherwise nobody could receive the link).
EMAIL_VERIFICATION=auto

# Images: prebuilt from the registry, or build locally with 'docker compose build'.
IMAGE_REGISTRY=ghcr.io/nihalnclt
IMAGE_TAG=latest

# Optional. Empty means off. See docs/self-hosting.md for what each enables.
RESEND_API_KEY=
EMAIL_FROM=Webyz <hello@$DOMAIN>
MAXMIND_LICENSE_KEY=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
PADDLE_API_KEY=
PADDLE_CLIENT_TOKEN=
PADDLE_WEBHOOK_SECRET=
PADDLE_ENVIRONMENT=
PADDLE_IP_ALLOWLIST=
CORS_ORIGINS=
LOG_LEVEL=info
EOF

chmod 600 "$OUT"
echo "Wrote $OUT for https://$DOMAIN"
echo "Next: docker compose up -d"
