#!/usr/bin/env sh
# Regenerate cloudflare-real-ip.conf from Cloudflare's published ranges, then
# test and reload the shared nginx. Run from infra/hosted/nginx on the server.
#
#   ./update-cloudflare-ips.sh            # writes the file next to this script
#   ./update-cloudflare-ips.sh --install  # also copies it into nginx and reloads
#
# Cloudflare changes these rarely; a monthly cron is plenty.
set -eu
cd "$(dirname "$0")"
v4=$(curl -fsS https://www.cloudflare.com/ips-v4)
v6=$(curl -fsS https://www.cloudflare.com/ips-v6)
[ -n "$v4" ] && [ -n "$v6" ] || { echo "empty response from Cloudflare; keeping the current file" >&2; exit 1; }
{
  echo "# Cloudflare's edge ranges, so \$remote_addr becomes the visitor's address"
  echo "# rather than Cloudflare's. Generated by update-cloudflare-ips.sh on $(date -u +%Y-%m-%d);"
  echo "# re-run it when Cloudflare changes the list (https://www.cloudflare.com/ips)."
  echo "# Included by webyz.conf. Only requests that arrive from these ranges have"
  echo "# CF-Connecting-IP honoured; a request that reaches the origin directly keeps"
  echo "# its real socket address and cannot forge one."
  printf '%s\n%s\n' "$v4" "$v6" | sed 's/^/set_real_ip_from /; s/$/;/'
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > cloudflare-real-ip.conf.new
mv cloudflare-real-ip.conf.new cloudflare-real-ip.conf
echo "wrote cloudflare-real-ip.conf ($(grep -c set_real_ip_from cloudflare-real-ip.conf) ranges)"
if [ "${1:-}" = "--install" ]; then
  NGINX_DIR="${NGINX_DIR:-$HOME/apps/nginx/conf.d}"
  cp cloudflare-real-ip.conf "$NGINX_DIR/cloudflare-real-ip.conf"
  docker exec nginx-proxy nginx -t && docker exec nginx-proxy nginx -s reload
  echo "installed and reloaded"
fi
