import crypto from "node:crypto";

import { ENCRYPTION_KEY, IS_PROD, GSC_ENABLED } from "../../config/env.js";

/**
 * At-rest encryption for the Search Console refresh token, which is a
 * long-lived credential to a customer's Google account. AES-256-GCM with a
 * random IV per value; the ciphertext carries a version prefix so the format
 * can change and so a legacy plaintext row (written before this existed) is
 * recognised and passed through until the site reconnects and re-encrypts.
 *
 * The key is ENCRYPTION_KEY, 64 hex characters (32 bytes), generated by
 * infra/setup.sh. Production refuses to start without it when Search Console
 * is enabled; development derives a fixed key so the feature still works
 * locally, with a warning so nobody mistakes that for a secret.
 */
const PREFIX = "enc:v1:";

const resolveKey = (): Buffer => {
  if (/^[0-9a-fA-F]{64}$/.test(ENCRYPTION_KEY)) return Buffer.from(ENCRYPTION_KEY, "hex");
  if (ENCRYPTION_KEY) {
    throw new Error("ENCRYPTION_KEY must be 64 hex characters (32 bytes); generate one with: openssl rand -hex 32");
  }
  if (IS_PROD && GSC_ENABLED) {
    throw new Error("ENCRYPTION_KEY is not set. Search Console stores a Google credential and needs it encrypted; generate one with: openssl rand -hex 32");
  }
  if (IS_PROD) {
    console.warn("[crypto] ENCRYPTION_KEY is not set; set it before enabling Search Console");
  } else {
    console.warn("[crypto] ENCRYPTION_KEY is not set; using a fixed development key");
  }
  return crypto.createHash("sha256").update("webyz-development-only-key").digest();
};

let key: Buffer | null = null;
const getKey = () => (key ??= resolveKey());

/** For tests: use an explicit key instead of the environment. */
export const encryptWithKey = (plaintext: string, k: Buffer): string => {
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv("aes-256-gcm", k, iv);
  const body = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return `${PREFIX}${iv.toString("base64url")}.${tag.toString("base64url")}.${body.toString("base64url")}`;
};

export const decryptWithKey = (stored: string, k: Buffer): string => {
  if (!stored.startsWith(PREFIX)) return stored; // legacy plaintext row
  const [iv, tag, body] = stored.slice(PREFIX.length).split(".");
  if (!iv || !tag || !body) throw new Error("Malformed encrypted value");
  const decipher = crypto.createDecipheriv("aes-256-gcm", k, Buffer.from(iv, "base64url"));
  decipher.setAuthTag(Buffer.from(tag, "base64url"));
  return Buffer.concat([decipher.update(Buffer.from(body, "base64url")), decipher.final()]).toString("utf8");
};

export const isEncrypted = (stored: string): boolean => stored.startsWith(PREFIX);

export const encryptSecret = (plaintext: string): string => encryptWithKey(plaintext, getKey());
export const decryptSecret = (stored: string): string => decryptWithKey(stored, getKey());
